# Generated by Django 3.0.6 on 2020-05-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('profile', models.ImageField(upload_to='images/')),
                ('summery', models.TextField()),
                ('extrapick_1', models.ImageField(blank=True, upload_to='images/')),
                ('extrapick_2', models.ImageField(blank=True, upload_to='images/')),
                ('extrapick_3', models.ImageField(blank=True, upload_to='images/')),
                ('extrapick_4', models.ImageField(blank=True, upload_to='images/')),
                ('extrapick_5', models.ImageField(blank=True, upload_to='images/')),
                ('directory_address', models.CharField(max_length=175)),
            ],
        ),
    ]
