# Generated by Django 3.0.6 on 2020-05-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animetitles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animetitle',
            name='extrapick_6',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
