# Generated by Django 3.0.6 on 2020-05-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animetitles', '0002_animetitle_extrapick_6'),
    ]

    operations = [
        migrations.AddField(
            model_name='animetitle',
            name='trailer',
            field=models.CharField(default='No_Trailer_Given', max_length=170),
            preserve_default=False,
        ),
    ]
