# Generated by Django 3.0.6 on 2020-06-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animetitles', '0003_animetitle_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='animetitle',
            name='genres',
            field=models.FilePathField(default='asdd/asd'),
            preserve_default=False,
        ),
    ]
