# Generated by Django 3.0.6 on 2020-06-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animetitles', '0005_auto_20200601_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='animetitle',
            name='otherNames',
            field=models.CharField(default='put OTHER_NAMES here', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animetitle',
            name='trailer',
            field=models.CharField(blank=True, max_length=170),
        ),
    ]
