# Generated by Django 3.0.6 on 2020-09-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animetitles', '0006_auto_20200606_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='animetitle',
            name='watchCurrEp',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
