# Generated by Django 3.0.6 on 2021-03-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animetitles', '0007_animetitle_watchcurrep'),
    ]

    operations = [
        migrations.AddField(
            model_name='animetitle',
            name='mal_anime_link',
            field=models.CharField(blank=True, default=0, max_length=250),
        ),
        migrations.AlterField(
            model_name='animetitle',
            name='watchCurrEp',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
