# Generated by Django 3.0.6 on 2021-03-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animetitles', '0008_auto_20210327_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animetitle',
            name='mal_anime_link',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
